name: Publish release

on:
    release:
        types: [published]

jobs:
    publish-release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout latest source
              uses: actions/checkout@v2

            - name: Set up JDK 8
              uses: actions/setup-java@v1
              with:
                  java-version: 1.8

            - name: Grant execute permission for gradlew
              run: chmod +x gradlew

            - name: Publish to Maven Central
              run: |
                  NEW_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
                  echo "New version: ${NEW_VERSION}"
                  ./gradlew -Pversion=${NEW_VERSION} -PMAVEN_SIGNING_KEY_ID=${{ secrets.MAVEN_SIGNING_KEY_ID }} -PMAVEN_SIGNING_KEY=${{ secrets.MAVEN_SIGNING_KEY }} -PMAVEN_SIGNING_PASSWORD=${{ secrets.MAVEN_SIGNING_PASSWORD }} -PMAVEN_CENTRAL_USERNAME=${{ secrets.MAVEN_CENTRAL_USERNAME }} -PMAVEN_CENTRAL_PASSWORD=${{ secrets.MAVEN_CENTRAL_PASSWORD }} publish
